### ISSUE TITLE
Can't login to GUI as LAPSadmin

### ISSUE THREAD

**Issue by nateships** [PezzaD84/macOSLAPS#1]
Everything working great on v3

Terminal login and su works great

Cannot login at the login window to LAPSadmin, in Jamf Connect Login it freezes, at Mac OS default login it spins forever

**Comment by PezzaD84** [comment]
Hi,

Thanks for raising this. I have been meaning to add a known issues page as this issue has been raised before. I am working 
on this but it seems to be an issue when an account is created by a script.

I will update this issue ticket once I manage to fix it.

Thank you.

**Comment by PezzaD84** [comment]
Hi,

This issue has now been resolved in v4 of the LAPS script which is now available.
