### ISSUE TITLE
Crypt key and secret key fail

### ISSUE THREAD

**Issue by MrMarl3y** [PezzaD84/macOSLAPS#10]
Good afternoon

I have configured your LAPS and have it tested on a total of 5 computers. I have confirmed that all of them work without an issue. I have another MAC I am trying to install and get working but every time I run  the command it successfully installs the program but it fails to send the cryptkey and secrectkey to JAMF. It is currently on Big Sur and can not be upgraded any further due to its age. Any insight is appreciated.

**Comment by PezzaD84** [comment]
Hi @MrMarl3y 

Are you able to share the jamf policy logs and the local laps logs please? if you look in /Library/.LAPS/Logs/ there is a file in there and then also the logs of the policy running.
I will look through the logs and see what I can spot thats potentially the issue.

**Comment by MrMarl3y** [comment]
***** LAPS Account creation 06/07/2023 14:45:14
Password length has been set to 14 characters
MacLaps does not exist. Creating local admin now
LAPS Account created Successfully
Device serial is D*************
JAMF ID is 
LAPS Configuration has failed
Cryptkey has not been successfully configured
SecretKey has not been successfully configured

**Comment by PezzaD84** [comment]
Ok so looking at that log I would say either the API credentials failed or the internet connection dropped during setup. If the LOG doesn't show a JAMF ID then the API call has not received a response from JAMF.
