### ISSUE TITLE
Teams integration

### ISSUE THREAD

**Issue by nirvanaboi10** [PezzaD84/macOSLAPS#13]
Saw your presentation at JNUC and thought id take a crack at teams notification as its what's used for my company. Added a few lines to allow for teams web hook notification. Thought you would be interested. Code for decode is after the # Final Decoder checks for password rotation# as I wanted to include the time frame the account would be reset in the notification. Decoder also wasn't pasting the code to the clipboard so added that as well.

[Create:Cycle.txt](https://github.com/PezzaD84/macOSLAPS/files/12752671/Create.Cycle.txt)
[Decoder.txt](https://github.com/PezzaD84/macOSLAPS/files/12752672/Decoder.txt)

**Comment by PezzaD84** [comment]
Hi @nirvanaboi10 

Thank you very much for watching the presentation it means a lot to hear back from people. This is awesome work mate thanks for putting the time in to create this. Teams integration is something I have been looking to add for a while so this has done half the work for me now! 
It's also given me the idea to add the "Password will reset" time stamp into the Slack notification, I like that😁
I will of course give you credit in the script for anything I use 😉
