### ISSUE TITLE
swiftDialog version

### ISSUE THREAD

**Issue by azgmacos** [PezzaD84/macOSLAPS#14]
hey there, this is overwriting the current version of swiftDialog I have installed each time, can it be removed from the package and built into the script to check for the latest?

**Comment by PezzaD84** [comment]
Hi @azgmacos 
The laps decoder script should be checking for swiftdialog and only installs if needed or an update is needed.
Which version of the script are you currently using?
Can you share the logs if possible?
Thanks

**Comment by azgmacos** [comment]
This is the latest package downloaded from github….

Built into the actual package (not the script) swiftDialog version 1.11.2 is installing over and over each time as it reinstalls the LAPS package (as shown in the setup guide). Please see screenshot of Jamf setup.

Please see the attached screenshot of suspicious package (on latest version downloaded from Github. For now ,I just made my own branding package and removed the swiftDialog with composer…

Thank you for creating this LAPS solution, I saw your presentation at JNUC and I really liked it!

Also, couple of other smaller feature suggestions (which I did for my own implementation)

  1.  Option to set a custom home folder path for the account
  2.  Option to hide the account on creation

Hope this is helpful 😊

Subject: [EXTERNAL] Re: [PezzaD84/macOSLAPS] swiftDialog version (Issue #14)

Hi @azgmacos<https://urldefense.com/v3/__https:/github.com/azgmacos__;!!Ny3gXNNm!4CdULeOxjB12U-RDztbLjuCX9m84300y7xtq6ZfO4hGnSal9ObLszqWo9UuyPqmOeV6ug9ocTjaWdOerOoFsy05R9khr9Wob$>
The laps decoder script should be checking for swiftdialog and only installs if needed or an update is needed.
Which version of the script are you currently using?
Can you share the logs if possible?
Thanks

**Comment by azgmacos** [comment]
<img width="1310" alt="Screenshot 2023-10-17 at 11 36 07 AM" src="https://github.com/PezzaD84/macOSLAPS/assets/147692872/c2620e72-3c10-4b95-8a16-3108bcaea51d">
<img width="1251" alt="Screenshot 2023-10-17 at 11 35 01 AM" src="https://github.com/PezzaD84/macOSLAPS/assets/147692872/80d4eb6f-cada-4d4c-837f-0babca8437ad">

**Comment by PezzaD84** [comment]
Ahhh I'm with you now!
This is my mistake which I've only just seen. The newer version no longer needs the PKG file as the images are now hosted in GitHub. I was updating the wiki page but must have missed the part where I noted the PKG is no longer needed in the new versions.

**Comment by PezzaD84** [comment]
Also thanks for checking out my jnuc session it's awesome to hear feedback like this and take feature requests.
The option to hide the account is something I've been looking to add but I'm running out of script variables within JAMF for these extras to be added. At the moment you can prefix the account name with an underscore. For example _lapsadmin would create the account hidden.
