### ISSUE TITLE
Error Creating LAPS Admin

### ISSUE THREAD

**Issue by jonptr** [PezzaD84/macOSLAPS#16]
Getting the following logs while try to create LAPS Admin. Could you please help @PezzaD84 

Script result: Error checking any previous configuration.....
Log found. Checking for previous failures.....
No previous failures detected. Continuing LAPS Configuration.....
Log already exists. Continuing setup.....
=================================================================
============ LAPS Account cycled 19/12/2023 15:35:49 ============
=================================================================
Password length has been set to 10 characters
A Special character has been set in the password
eximpe-admin does not exist. Creating local admin now
2023-12-19 15:35:50.243 sysadminctl[45965:953412] ----------------------------
2023-12-19 15:35:50.244 sysadminctl[45965:953412] No clear text password or interactive option was specified (adduser, change/reset password will not allow user to use FDE) !
2023-12-19 15:35:50.245 sysadminctl[45965:953412] ----------------------------
2023-12-19 15:35:50.256 sysadminctl[45965:953412] New account password error.  (5402)
/Library/Application Support/JAMF/tmp/laps create account: line 264: /Users/eximpe-admin/Library/Preferences/com.apple.SetupAssistant.plist: No such file or directory
chown: eximpe-admin: illegal user name
chmod: /Users/eximpe-admin/Library/Preferences/com.apple.SetupAssistant.plist: No such file or directory
<?xml version="1.0" encoding="UTF-8"?><computer><id>2</id></computer><?xml version="1.0" encoding="UTF-8"?><computer><id>2</id></computer>CryptKey and SecretKey Escrowed to Jamf successfully
Device serial is C02X305FJG5H
JAMF ID is 2
LAPS Configuration was successful
No slack URL configured
No Teams Webhook configured
LAPS Launch Daemon found. Removing old Launch Daemon.
Launch Daemon removed.

**Comment by PezzaD84** [comment]
Hi @jonptr ,

Do you have a password policy which the LAPS password is not meeting? This line `2023-12-19 15:35:50.256 sysadminctl[45965:953412] New account password error. (5402)` usually means the password doesn't meet requirements.

**Comment by jonptr** [comment]
@PezzaD84 This issue is resolved. I modified the password code to meet the organisation policy.
