### ISSUE TITLE
The password is NOT automatically copied to clipboard.

### ISSUE THREAD

**Issue by rhype** [PezzaD84/macOSLAPS#17]
Hi @PezzaD84 
I hope you're doing well. I've been using macLAPS, and it's been great so far. I appreciate all your hard work! I've noticed that the password isn't automatically copied to the clipboard. Is there something I might be doing wrong, and is there a way I can fix it? Thanks a bunch!

**Comment by PezzaD84** [comment]
Hi @rhype 

Thanks for bringing this to my attention I must have removed the line by mistake when making some edits. I've put it back in now so if you update your decoder script to the one on github it will now copy automatically.

Let me know how you get on.

**Comment by rhype** [comment]
@PezzaD84 
Thanks for clearing this up, now it works as described in the Wiki. Cheers!
