### ISSUE TITLE
Unable to login/authenicate with LAPS account

### ISSUE THREAD

**Issue by ysdevgan** [PezzaD84/macOSLAPS#18]
Hi @PezzaD84,

I am piloting this solution. LAPS account is created successfully and password decode is working as expected however I am unable to authenticate/login using LAPS account.

**Comment by PezzaD84** [comment]
Hi @ysdevgan 

At what point is the authentication failing? Is this at the login screen or trying to authenticate an installation? If you copy and paste the password to a text file can you see any spaces before or after the password? Would you be able to share a short screen recording of the issue?

**Comment by ysdevgan** [comment]
Thanks for the prompt response. I manually entered the password for package installation after pasting to notes. There are no white spaces before or after. Will share screenshots shortly.

________________________________

**Comment by PezzaD84** [comment]
Thanks for the update.

If you can share the laps logs as well I can take a look to see if anything failed and maybe the password wasnt created correctly.
The logs are in /Library/.LAPS/Logs/
