### ISSUE TITLE
Jamf Account Privileges required for API calls

### ISSUE THREAD

**Issue by marcelpogorzelski** [PezzaD84/macOSLAPS#2]
Do you know what privileges are required for the account that is going to do the API calls?

**Comment by PezzaD84** [comment]
Hi,

You can strip out all permissions and add the minimum API permissions that are needed.
They are as follows:
API Intergrations: C,R,U
Computer Extension Attributes: C,R,U
Computers: C,R,U
User Extension Attributes: C,R,U
Users: C,R,U
