### ISSUE TITLE
local admin account already exist

### ISSUE THREAD

**Issue by duhh24** [PezzaD84/macOSLAPS#22]
where can I find the prescript for Jamf to delete the existing account and overwrite it with a LAPS admin account.

Thanks!

**Comment by PezzaD84** [comment]
Hi @duhh24 

There isn't a generic script to use but rather I can create one for you or you can create your own?
I've written scripts for customers before to do this but some people dont want to give out their admin account names to me as it's a bit of a security risk I guess.
