### ISSUE TITLE
Message not closing after 10 seconds

### ISSUE THREAD

**Issue by rhype** [PezzaD84/macOSLAPS#23]
Posting here in case others are experiencing this, the LAPS password message is not closing after 10 seconds. It remains static on the screen unless the process is killed.

**Comment by PezzaD84** [comment]
@rhype thanks for mentioning this. I had a few users raise this the other day and it seems to be a bug in the latest version of Swift Dialog. I have changed the Decoder script now and the message is back to how it should be. You can download the latest version from my github or change the line with the timer key to `--timer 10 \`
