### ISSUE TITLE
Cleaner suppress plist 

### ISSUE THREAD

**Issue by marcelpogorzelski** [PezzaD84/macOSLAPS#3]
Here is a cleaner way of adding the Setup Assistent suppress plist. This way there is no need to set file permission.
I also added  DidSeeAccessibility, DidSeeAppearanceSetup and DidSeePrivacy.

`# Create Setup Assistant suppress plist
    setup_assistant_file="/Users/$4/Library/Preferences/com.apple.SetupAssistant.plist"
    sudo -u $4 defaults write "$setup_assistant_file" DidSeeAccessibility -bool true
    sudo -u $4 defaults write "$setup_assistant_file" DidSeeAppearanceSetup -bool true
    sudo -u $4 defaults write "$setup_assistant_file" DidSeeAvatarSetup -bool true
    sudo -u $4 defaults write "$setup_assistant_file" DidSeeCloudSetup -bool true
    sudo -u $4 defaults write "$setup_assistant_file" DidSeePrivacy -bool true
    sudo -u $4 defaults write "$setup_assistant_file" DidSeeSiriSetup -bool true
    sudo -u $4 defaults write "$setup_assistant_file" DidSeeSyncSetup -bool true
    sudo -u $4 defaults write "$setup_assistant_file" DidSeeSyncSetup2 -bool true
    sudo -u $4 defaults write "$setup_assistant_file" DidSeeTouchIDSetup -bool true
    sudo -u $4 defaults write "$setup_assistant_file" DidSeeiCloudLoginForStorageServices -bool true
    sudo -u $4 defaults write "$setup_assistant_file" DidSeeiCloudSecuritySetup -bool true
    sudo -u $4 defaults write "$setup_assistant_file" GestureMovieSeen -bool true
    sudo -u $4 defaults write "$setup_assistant_file" LastSeenBuddyBuildVersion -string "21C52"
    sudo -u $4 defaults write "$setup_assistant_file" LastSeenCloudProductVersion -string "12.2.1"`

**Comment by PezzaD84** [comment]
Thanks for this. I'll add this for consideration in the next version update👍🏻
