### ISSUE TITLE
Question - extension attributes

### ISSUE THREAD

**Issue by jelockwood** [PezzaD84/macOSLAPS#7]
@PezzaD84 
I must confess I am slightly confused about which is which in terms of LAPS CryptKey and LAPS Secret.

Which contains the encrypted LAPS password?
Which contains the key used to decrypt the encrypted LAPS password?

Looking at your scripts implies LAPS Secret contains the encryption key and LAPS CryptKey contains the encrypted local admin password but their _names_ would imply the opposite.

**Comment by PezzaD84** [comment]
@jelockwood 
You are correct about which key contains which item. cryptKey came from shortening EncryptedKey and secret is secret. Just a way to keep track of things but at the same time keep it short.
