### ISSUE TITLE
i cant find my Encrypted API Credentials

### ISSUE THREAD

**Issue by fabu1987** [PezzaD84/macOSLAPS#8]
where do I find my Encrypted API credentials exactly?
no matter what I give in the parameter there, it doesn't work

**Comment by PezzaD84** [comment]
hi @fabu1987 

You can use this script here to encode your API account. https://github.com/PezzaD84/macOSLAPS/blob/main/Encode%20API%20Credentials

You need to save and run it locally on your device and not run it from jamf or as part of the LAPS scripts. Run the script from terminal and it will echo out a random string which is your encoded API credentials

**Comment by fabu1987** [comment]
hello pezzD84

thank you for your fast answer!!! 
now it's clear to me i'll procure this one.... now i see the following in the jamf on the client.....

![image](https://github.com/PezzaD84/macOSLAPS/assets/137278260/405ee133-f20b-4a75-b6a8-e85dc210221a)


and the password remains empty :-(
![image](https://github.com/PezzaD84/macOSLAPS/assets/137278260/78fa99b6-dd88-4f58-a5f6-a6bd77632671)



do you have any idea :-/

**Comment by fabu1987** [comment]
Sorry ..... but I can't find why the password is always empty

**Comment by PezzaD84** [comment]
Hi @fabu1987 

Sorry I've taken so long to reply work has been hectic!

It looks like the API credentials are not working as the encoded credentials are not being populated in the extension attributes. Can you share the logs from JAMF and the local log in /Library/.LAPS/Logs/

Sometimes JAMF also requires you to log in at least once to the JAMF portal with the API account just incase it needs to reset the password or make sure it meets security requirements.
